create table if not exists public.historial_consumo (
    id bigint generated by default as identity primary key,
    nombre text not null,
    cantidad real not null check (cantidad > 0),
    unidad text,
    categoria_id bigint,
    fecha_consumo timestamptz not null default now(),
    user_id uuid not null references auth.users(id) on delete cascade
);

create index if not exists historial_consumo_user_fecha_idx
    on public.historial_consumo (user_id, fecha_consumo);

alter table public.historial_consumo enable row level security;

grant select, insert, delete on table public.historial_consumo to authenticated;
grant usage, select on sequence public.historial_consumo_id_seq to authenticated;

drop policy if exists "Users can read their consumption history" on public.historial_consumo;
create policy "Users can read their consumption history"
    on public.historial_consumo for select
    using (auth.uid() = user_id);

drop policy if exists "Users can insert their consumption history" on public.historial_consumo;
create policy "Users can insert their consumption history"
    on public.historial_consumo for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can delete their consumption history" on public.historial_consumo;
create policy "Users can delete their consumption history"
    on public.historial_consumo for delete
    using (auth.uid() = user_id);
